package pe.com.segrop.sgsapp.domain;
// Generated 27-mar-2012 23:44:26 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegCabCargo generated by hbm2java
 */
public class SegCabEntidad implements java.io.Serializable {

    private BigDecimal NCodEntidad;
    private String VNombre;
    private String VNombreApp;
    private String VDescripcion;
    private String VComentario;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private Set<SegDetAtributo> segDetAtributos = new HashSet<SegDetAtributo>(0);

    public SegCabEntidad() {
        super();
    }

    public SegCabEntidad(BigDecimal NCodEntidad) {
        this.NCodEntidad = NCodEntidad;
    }

    public SegCabEntidad(BigDecimal NCodEntidad, String VNombre, String VNombreApp, String VDescripcion, String VComentario, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, Set<SegDetAtributo> segDetAtributos) {
        this.NCodEntidad = NCodEntidad;
        this.VNombre = VNombre;
        this.VNombreApp = VNombreApp;
        this.VDescripcion = VDescripcion;
        this.VComentario = VComentario;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.segDetAtributos = segDetAtributos;
    }

    public BigDecimal getNCodEntidad() {
        return this.NCodEntidad;
    }

    public void setNCodEntidad(BigDecimal NCodEntidad) {
        this.NCodEntidad = NCodEntidad;
    }

    public String getVNombre() {
        return VNombre;
    }

    public void setVNombre(String VNombre) {
        this.VNombre = VNombre;
    }

    public String getVNombreApp() {
        return VNombreApp;
    }

    public void setVNombreApp(String VNombreApp) {
        this.VNombreApp = VNombreApp;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public String getVComentario() {
        return VComentario;
    }

    public void setVComentario(String VComentario) {
        this.VComentario = VComentario;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Set<SegDetAtributo> getSegDetAtributos() {
        return segDetAtributos;
    }

    public void setSegDetAtributos(Set<SegDetAtributo> segDetAtributos) {
        this.segDetAtributos = segDetAtributos;
    }
}
