package pe.com.segrop.sgsapp.domain;
// Generated 15-jul-2012 21:05:20 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegCabUsuario generated by hbm2java
 */
public class SegCabUsuario implements java.io.Serializable {

    private SegCabUsuarioId id;
    private BigDecimal NCodUsuario;
    private BigDecimal NCodEmpresa;
    private String VNombres;
    private String VApellidos;
    private String VUsuario;
    private String VCorreo;
    private String VMovil;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private BigDecimal NTipNumDocumento;
    private String VNumDocumento;
    private BigDecimal NFlgClave;
    private BigDecimal NFlgCambioclave;
    private Set<SegRelUsuarioperfil> segRelUsuarioperfils = new HashSet<SegRelUsuarioperfil>(0);
    private Set<SegDetClave> segDetClaves = new HashSet<SegDetClave>(0);

    public SegCabUsuario() {
        super();
    }

    public SegCabUsuario(SegCabUsuarioId id, BigDecimal NCodUsuario, BigDecimal NCodEmpresa) {
        this.id = id;
        this.NCodUsuario = NCodUsuario;
        this.NCodEmpresa = NCodEmpresa;
    }

    public SegCabUsuario(SegCabUsuarioId id, BigDecimal NCodUsuario, BigDecimal NCodEmpresa, String VNombres, String VApellidos, String VUsuario, String VCorreo, String VMovil, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, BigDecimal NTipNumDocumento, String VNumDocumento, BigDecimal NFlgClave, BigDecimal NFlgCambioclave, Set<SegRelUsuarioperfil> segRelUsuarioperfils, Set<SegDetClave> segDetClaves) {
        this.id = id;
        this.NCodUsuario = NCodUsuario;
        this.NCodEmpresa = NCodEmpresa;
        this.VNombres = VNombres;
        this.VApellidos = VApellidos;
        this.VUsuario = VUsuario;
        this.VCorreo = VCorreo;
        this.VMovil = VMovil;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.NTipNumDocumento = NTipNumDocumento;
        this.VNumDocumento = VNumDocumento;
        this.NFlgClave = NFlgClave;
        this.NFlgCambioclave = NFlgCambioclave;
        this.segRelUsuarioperfils = segRelUsuarioperfils;
        this.segDetClaves = segDetClaves;
    }

    public SegCabUsuarioId getId() {
        return this.id;
    }

    public void setId(SegCabUsuarioId id) {
        this.id = id;
    }

    /**
     * @return the NCodUsuario
     */
    public BigDecimal getNCodUsuario() {
        return NCodUsuario;
    }

    /**
     * @param NCodUsuario the NCodUsuario to set
     */
    public void setNCodUsuario(BigDecimal NCodUsuario) {
        this.NCodUsuario = NCodUsuario;
    }

    /**
     * @return the NCodEmpresa
     */
    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    /**
     * @param NCodEmpresa the NCodEmpresa to set
     */
    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public String getVNombres() {
        return this.VNombres;
    }

    public void setVNombres(String VNombres) {
        this.VNombres = VNombres;
    }

    public String getVApellidos() {
        return this.VApellidos;
    }

    public void setVApellidos(String VApellidos) {
        this.VApellidos = VApellidos;
    }

    public String getVUsuario() {
        return this.VUsuario;
    }

    public void setVUsuario(String VUsuario) {
        this.VUsuario = VUsuario;
    }

    public String getVCorreo() {
        return this.VCorreo;
    }

    public void setVCorreo(String VCorreo) {
        this.VCorreo = VCorreo;
    }

    public String getVMovil() {
        return this.VMovil;
    }

    public void setVMovil(String VMovil) {
        this.VMovil = VMovil;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public BigDecimal getNTipNumDocumento() {
        return this.NTipNumDocumento;
    }

    public void setNTipNumDocumento(BigDecimal NTipNumDocumento) {
        this.NTipNumDocumento = NTipNumDocumento;
    }

    public String getVNumDocumento() {
        return this.VNumDocumento;
    }

    public void setVNumDocumento(String VNumDocumento) {
        this.VNumDocumento = VNumDocumento;
    }

    public BigDecimal getNFlgClave() {
        return this.NFlgClave;
    }

    public void setNFlgClave(BigDecimal NFlgClave) {
        this.NFlgClave = NFlgClave;
    }

    public BigDecimal getNFlgCambioclave() {
        return this.NFlgCambioclave;
    }

    public void setNFlgCambioclave(BigDecimal NFlgCambioclave) {
        this.NFlgCambioclave = NFlgCambioclave;
    }

    public Set<SegRelUsuarioperfil> getSegRelUsuarioperfils() {
        return this.segRelUsuarioperfils;
    }

    public void setSegRelUsuarioperfils(Set<SegRelUsuarioperfil> segRelUsuarioperfils) {
        this.segRelUsuarioperfils = segRelUsuarioperfils;
    }

    public Set<SegDetClave> getSegDetClaves() {
        return this.segDetClaves;
    }

    public void setSegDetClaves(Set<SegDetClave> segDetClaves) {
        this.segDetClaves = segDetClaves;
    }
}
