package pe.com.segrop.sgsapp.domain;
// Generated 27-ene-2012 2:54:45 by Hibernate Tools 3.2.1.GA

import java.io.File;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegCabEmpresa generated by hbm2java
 */
public class SegCabEmpresa implements java.io.Serializable {

    private BigDecimal NCodEmpresa;
    private String VRuc;
    private String VRazonSocial;
    private String VDireccion;
    private String VTelefono;
    private String VRutaLogo;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private Set<SegCabUsuario> segCabUsuarios = new HashSet<SegCabUsuario>(0);
    private Set<SegDetPerfil> segDetPerfils = new HashSet<SegDetPerfil>(0);
    private Set<SegDetDocumento> segDetDocumentos = new HashSet<SegDetDocumento>(0);
    private File file;

    public SegCabEmpresa() {
        super();
    }

    public SegCabEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public SegCabEmpresa(BigDecimal NCodEmpresa, String VRuc, String VRazonSocial, String VDireccion, String VTelefono, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, Set<SegCabUsuario> segCabUsuarios, Set<SegDetPerfil> segDetPerfils, Set<SegDetDocumento> segDetDocumentos) {
        this.NCodEmpresa = NCodEmpresa;
        this.VRuc = VRuc;
        this.VRazonSocial = VRazonSocial;
        this.VDireccion = VDireccion;
        this.VTelefono = VTelefono;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.segCabUsuarios = segCabUsuarios;
        this.segDetPerfils = segDetPerfils;
        this.segDetDocumentos = segDetDocumentos;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public String getVRuc() {
        return this.VRuc;
    }

    public void setVRuc(String VRuc) {
        this.VRuc = VRuc;
    }

    public String getVRazonSocial() {
        return this.VRazonSocial;
    }

    public void setVRazonSocial(String VRazonSocial) {
        this.VRazonSocial = VRazonSocial;
    }

    public String getVDireccion() {
        return this.VDireccion;
    }

    public void setVDireccion(String VDireccion) {
        this.VDireccion = VDireccion;
    }

    public String getVTelefono() {
        return this.VTelefono;
    }

    public void setVTelefono(String VTelefono) {
        this.VTelefono = VTelefono;
    }

    public String getVRutaLogo() {
        return VRutaLogo;
    }

    public void setVRutaLogo(String VRutaLogo) {
        this.VRutaLogo = VRutaLogo;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Set<SegCabUsuario> getSegCabUsuarios() {
        return this.segCabUsuarios;
    }

    public void setSegCabUsuarios(Set<SegCabUsuario> segCabUsuarios) {
        this.segCabUsuarios = segCabUsuarios;
    }

    public Set<SegDetPerfil> getSegDetPerfils() {
        return this.segDetPerfils;
    }

    public void setSegDetPerfils(Set<SegDetPerfil> segDetPerfils) {
        this.segDetPerfils = segDetPerfils;
    }

    public Set<SegDetDocumento> getSegDetDocumentos() {
        return segDetDocumentos;
    }

    public void setSegDetDocumentos(Set<SegDetDocumento> segDetDocumentos) {
        this.segDetDocumentos = segDetDocumentos;
    }

    public File getFile() {
        return new File(this.VRutaLogo);
    }

    public void setFile(File file) {
        this.file = file;
    }
}
