package pe.com.segrop.sgsapp.domain;
// Generated 27-ene-2012 2:54:45 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SegCabMaestro generated by hbm2java
 */
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class SegCabMaestro implements java.io.Serializable {

    private BigDecimal NCodMaestro;
    private String VDescripcion;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private Set<SegDetMaestrodetalle> segDetMaestrodetalles = new HashSet<SegDetMaestrodetalle>(0);

    public SegCabMaestro() {
        super();
    }

    public SegCabMaestro(BigDecimal NCodMaestro) {
        this.NCodMaestro = NCodMaestro;
    }

    public SegCabMaestro(BigDecimal NCodMaestro, String VDescripcion, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, Set<SegDetMaestrodetalle> segDetMaestrodetalles) {
        this.NCodMaestro = NCodMaestro;
        this.VDescripcion = VDescripcion;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.segDetMaestrodetalles = segDetMaestrodetalles;
    }

    public BigDecimal getNCodMaestro() {
        return this.NCodMaestro;
    }

    public void setNCodMaestro(BigDecimal NCodMaestro) {
        this.NCodMaestro = NCodMaestro;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Set<SegDetMaestrodetalle> getSegDetMaestrodetalles() {
        return this.segDetMaestrodetalles;
    }

    public void setSegDetMaestrodetalles(Set<SegDetMaestrodetalle> segDetMaestrodetalles) {
        this.segDetMaestrodetalles = segDetMaestrodetalles;
    }
}
