package pe.com.segrop.sgsapp.domain;
// Generated 12-mar-2012 0:45:44 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetAccionesId generated by hbm2java
 */
public class SegDetAccionesId implements java.io.Serializable {

    private BigDecimal NCodAccion;
    private BigDecimal NCodNovedad;
    private BigDecimal NCodEmpresa;

    public SegDetAccionesId() {
        super();
    }

    public SegDetAccionesId(BigDecimal NCodAccion, BigDecimal NCodNovedad, BigDecimal NCodEmpresa) {
        this.NCodAccion = NCodAccion;
        this.NCodNovedad = NCodNovedad;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodAccion() {
        return this.NCodAccion;
    }

    public void setNCodAccion(BigDecimal NCodAccion) {
        this.NCodAccion = NCodAccion;
    }

    public BigDecimal getNCodNovedad() {
        return this.NCodNovedad;
    }

    public void setNCodNovedad(BigDecimal NCodNovedad) {
        this.NCodNovedad = NCodNovedad;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetAccionesId)) {
            return false;
        }
        SegDetAccionesId castOther = (SegDetAccionesId) other;

        return ((this.getNCodAccion() == castOther.getNCodAccion()) || (this.getNCodAccion() != null && castOther.getNCodAccion() != null && this.getNCodAccion().equals(castOther.getNCodAccion())))
                && ((this.getNCodNovedad() == castOther.getNCodNovedad()) || (this.getNCodNovedad() != null && castOther.getNCodNovedad() != null && this.getNCodNovedad().equals(castOther.getNCodNovedad())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodAccion() == null ? 0 : this.getNCodAccion().hashCode());
        result = 37 * result + (getNCodNovedad() == null ? 0 : this.getNCodNovedad().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
