package pe.com.segrop.sgsapp.domain;
// Generated 12-mar-2012 0:45:44 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegDetNovedad generated by hbm2java
 */
public class SegDetNovedad implements java.io.Serializable {

    private SegDetNovedadId id;
    private BigDecimal NCodNovedad;
    private BigDecimal NCodEmpresa;
    private BigDecimal NTipoNovedad;
    private BigDecimal NTipoEvento;
    private BigDecimal NPersona;
    private BigDecimal NActivo;
    private BigDecimal NProceso;
    private Boolean BPersona;
    private Boolean BActivo;
    private Boolean BProceso;
    private Date DFecHora;
    private String VDescBreve;
    private String VDescripcion;
    private BigDecimal NLocal;
    private BigDecimal NArea;
    private BigDecimal NLugar;
    private BigDecimal NResponsable;
    private BigDecimal NCargo;
    private String VAccTomadas;
    private BigDecimal NAnalisis;
    private BigDecimal NSeguimiento;
    private BigDecimal NEstado;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private Set<SegDetAcciones> segDetAccioneses = new HashSet<SegDetAcciones>(0);

    public SegDetNovedad() {
        super();
    }

    public SegDetNovedad(SegDetNovedadId id) {
        this.id = id;
    }

    public SegDetNovedad(SegDetNovedadId id, BigDecimal NCodNovedad, BigDecimal NCodEmpresa, BigDecimal NTipoNovedad, BigDecimal NTipoEvento, BigDecimal NPersona, BigDecimal NActivo, BigDecimal NProceso, Date DFecHora, String VDescBreve, String VDescripcion, BigDecimal NLocal, BigDecimal NArea, BigDecimal NLugar, BigDecimal NResponsable, BigDecimal NCargo, String VAccTomadas, BigDecimal NAnalisis, BigDecimal NSeguimiento, BigDecimal NEstado, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, Set<SegDetAcciones> segDetAccioneses) {
        this.id = id;
        this.NCodNovedad = NCodNovedad;
        this.NCodEmpresa = NCodEmpresa;
        this.NTipoNovedad = NTipoNovedad;
        this.NTipoEvento = NTipoEvento;
        this.NPersona = NPersona;
        this.NActivo = NActivo;
        this.NProceso = NProceso;
        this.DFecHora = DFecHora;
        this.VDescBreve = VDescBreve;
        this.VDescripcion = VDescripcion;
        this.NLocal = NLocal;
        this.NArea = NArea;
        this.NLugar = NLugar;
        this.NResponsable = NResponsable;
        this.NCargo = NCargo;
        this.VAccTomadas = VAccTomadas;
        this.NAnalisis = NAnalisis;
        this.NSeguimiento = NSeguimiento;
        this.NEstado = NEstado;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.segDetAccioneses = segDetAccioneses;
    }

    public SegDetNovedadId getId() {
        return this.id;
    }

    public void setId(SegDetNovedadId id) {
        this.id = id;
    }

    public BigDecimal getNCodNovedad() {
        return NCodNovedad;
    }

    public void setNCodNovedad(BigDecimal NCodNovedad) {
        this.NCodNovedad = NCodNovedad;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNTipoNovedad() {
        return this.NTipoNovedad;
    }

    public void setNTipoNovedad(BigDecimal NTipoNovedad) {
        this.NTipoNovedad = NTipoNovedad;
    }

    public BigDecimal getNTipoEvento() {
        return this.NTipoEvento;
    }

    public void setNTipoEvento(BigDecimal NTipoEvento) {
        this.NTipoEvento = NTipoEvento;
    }

    public BigDecimal getNPersona() {
        return NPersona;
    }

    public void setNPersona(BigDecimal NPersona) {
        this.NPersona = NPersona;
    }

    public BigDecimal getNActivo() {
        return NActivo;
    }

    public void setNActivo(BigDecimal NActivo) {
        this.NActivo = NActivo;
    }

    public BigDecimal getNProceso() {
        return NProceso;
    }

    public void setNProceso(BigDecimal NProceso) {
        this.NProceso = NProceso;
    }
    
    public Boolean getBPersona() {
        this.BPersona = this.getNPersona() != null ? this.getNPersona().intValue() == 1 ? true : false : false;
        return this.BPersona;
    }

    public void setBPersona(Boolean BPersona) {
        this.BPersona = BPersona;
        this.NPersona = BPersona ? BigDecimal.ONE : BigDecimal.ZERO;
    }

    public Boolean getBActivo() {
        this.BActivo = this.getNActivo() != null ? this.getNActivo().intValue() == 1 ? true : false : false;
        return this.BActivo;
    }

    public void setBActivo(Boolean BActivo) {
        this.BActivo = BActivo;
        this.NActivo = BActivo ? BigDecimal.ONE : BigDecimal.ZERO;
    }

    public Boolean getBProceso() {
        this.BProceso = this.getNProceso() != null ? this.getNProceso().intValue() == 1 ? true : false : false;
        return this.BProceso;
    }

    public void setBProceso(Boolean BProceso) {
        this.BProceso = BProceso;
        this.NProceso = BProceso ? BigDecimal.ONE : BigDecimal.ZERO;
    }

    public Date getDFecHora() {
        return this.DFecHora;
    }

    public void setDFecHora(Date DFecHora) {
        this.DFecHora = DFecHora;
    }

    public String getVDescBreve() {
        return this.VDescBreve;
    }

    public void setVDescBreve(String VDescBreve) {
        this.VDescBreve = VDescBreve;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public BigDecimal getNLocal() {
        return this.NLocal;
    }

    public void setNLocal(BigDecimal NLocal) {
        this.NLocal = NLocal;
    }

    public BigDecimal getNArea() {
        return this.NArea;
    }

    public void setNArea(BigDecimal NArea) {
        this.NArea = NArea;
    }

    public BigDecimal getNLugar() {
        return this.NLugar;
    }

    public void setNLugar(BigDecimal NLugar) {
        this.NLugar = NLugar;
    }

    public BigDecimal getNResponsable() {
        return this.NResponsable;
    }

    public void setNResponsable(BigDecimal NResponsable) {
        this.NResponsable = NResponsable;
    }

    public BigDecimal getNCargo() {
        return this.NCargo;
    }

    public void setNCargo(BigDecimal NCargo) {
        this.NCargo = NCargo;
    }

    public String getVAccTomadas() {
        return this.VAccTomadas;
    }

    public void setVAccTomadas(String VAccTomadas) {
        this.VAccTomadas = VAccTomadas;
    }
    
    public BigDecimal getNAnalisis() {
        return this.NAnalisis;
    }

    public void setNAnalisis(BigDecimal NAnalisis) {
        this.NAnalisis = NAnalisis;
    }

    public BigDecimal getNSeguimiento() {
        return this.NSeguimiento;
    }

    public void setNSeguimiento(BigDecimal NSeguimiento) {
        this.NSeguimiento = NSeguimiento;
    }

    public BigDecimal getNEstado() {
        return NEstado;
    }

    public void setNEstado(BigDecimal NEstado) {
        this.NEstado = NEstado;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Set<SegDetAcciones> getSegDetAccioneses() {
        return this.segDetAccioneses;
    }

    public void setSegDetAccioneses(Set<SegDetAcciones> segDetAccioneses) {
        this.segDetAccioneses = segDetAccioneses;
    }
}
