package pe.com.segrop.sgsapp.domain;
// Generated 27-ene-2012 2:54:45 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SegDetMaestrodetalle generated by hbm2java
 */
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class SegDetMaestrodetalle implements java.io.Serializable {

    private BigDecimal NCodMaestro;
    private BigDecimal NCodMaestrodetalle;
    private SegCabMaestro segCabMaestro;
    private String VDescripcion;
    private BigDecimal NEstado;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;

    public SegDetMaestrodetalle() {
        super();
    }

    public SegDetMaestrodetalle(BigDecimal NCodMaestrodetalle, SegCabMaestro segCabMaestro) {
        this.NCodMaestrodetalle = NCodMaestrodetalle;
        this.segCabMaestro = segCabMaestro;
    }

    public SegDetMaestrodetalle(BigDecimal NCodMaestro, BigDecimal NCodMaestrodetalle, SegCabMaestro segCabMaestro, String VDescripcion, BigDecimal NEstado, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion) {
        this.NCodMaestro = NCodMaestro;
        this.NCodMaestrodetalle = NCodMaestrodetalle;
        this.segCabMaestro = segCabMaestro;
        this.VDescripcion = VDescripcion;
        this.NEstado = NEstado;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
    }

    public BigDecimal getNCodMaestro() {
        return NCodMaestro;
    }

    public void setNCodMaestro(BigDecimal NCodMaestro) {
        this.NCodMaestro = NCodMaestro;
    }

    public BigDecimal getNCodMaestrodetalle() {
        return this.NCodMaestrodetalle;
    }

    public void setNCodMaestrodetalle(BigDecimal NCodMaestrodetalle) {
        this.NCodMaestrodetalle = NCodMaestrodetalle;
    }

    public SegCabMaestro getSegCabMaestro() {
        return this.segCabMaestro;
    }

    public void setSegCabMaestro(SegCabMaestro segCabMaestro) {
        this.segCabMaestro = segCabMaestro;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public BigDecimal getNEstado() {
        return this.NEstado;
    }

    public void setNEstado(BigDecimal NEstado) {
        this.NEstado = NEstado;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }
}
