package pe.com.segrop.sgsapp.domain;
// Generated 16-mar-2012 0:40:39 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetPerfilId generated by hbm2java
 */
public class SegDetPerfilId implements java.io.Serializable {

    private BigDecimal NCodPerfil;
    private BigDecimal NCodEmpresa;

    public SegDetPerfilId() {
        super();
    }

    public SegDetPerfilId(BigDecimal NCodPerfil, BigDecimal NCodEmpresa) {
        this.NCodPerfil = NCodPerfil;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodPerfil() {
        return this.NCodPerfil;
    }

    public void setNCodPerfil(BigDecimal NCodPerfil) {
        this.NCodPerfil = NCodPerfil;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetPerfilId)) {
            return false;
        }
        SegDetPerfilId castOther = (SegDetPerfilId) other;

        return ((this.getNCodPerfil() == castOther.getNCodPerfil()) || (this.getNCodPerfil() != null && castOther.getNCodPerfil() != null && this.getNCodPerfil().equals(castOther.getNCodPerfil())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodPerfil() == null ? 0 : this.getNCodPerfil().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
