package pe.com.segrop.sgsapp.domain;
// Generated 21-feb-2012 0:26:46 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetAtributoId generated by hbm2java
 */
public class SegDetAtributoId implements java.io.Serializable {

    private BigDecimal NCodEntidad;
    private BigDecimal NCodAtributo;

    public SegDetAtributoId() {
        super();
    }

    public SegDetAtributoId(BigDecimal NCodEntidad, BigDecimal NCodAtributo) {
        this.NCodEntidad = NCodEntidad;
        this.NCodAtributo = NCodAtributo;
    }

    public BigDecimal getNCodEntidad() {
        return this.NCodEntidad;
    }

    public void setNCodEntidad(BigDecimal NCodEntidad) {
        this.NCodEntidad = NCodEntidad;
    }

    public BigDecimal getNCodAtributo() {
        return this.NCodAtributo;
    }

    public void setNCodAtributo(BigDecimal NCodAtributo) {
        this.NCodAtributo = NCodAtributo;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetAtributoId)) {
            return false;
        }
        SegDetAtributoId castOther = (SegDetAtributoId) other;

        return ((this.getNCodEntidad() == castOther.getNCodEntidad()) || (this.getNCodEntidad() != null && castOther.getNCodEntidad() != null && this.getNCodEntidad().equals(castOther.getNCodEntidad())))
                && ((this.getNCodAtributo() == castOther.getNCodAtributo()) || (this.getNCodAtributo() != null && castOther.getNCodAtributo() != null && this.getNCodAtributo().equals(castOther.getNCodAtributo())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodEntidad() == null ? 0 : this.getNCodEntidad().hashCode());
        result = 37 * result + (getNCodAtributo() == null ? 0 : this.getNCodAtributo().hashCode());
        return result;
    }
}
