package pe.com.segrop.sgsapp.domain;
// Generated 12-mar-2012 0:45:44 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SegDetAcciones generated by hbm2java
 */
public class SegDetAcciones implements java.io.Serializable {

    private SegDetAccionesId id;
    private SegDetNovedad segDetNovedad;
    private BigDecimal NCodAccion;
    private BigDecimal NCodNovedad;
    private BigDecimal NCodEmpresa;
    private String VDescripcion;
    private Date DFecHora;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;

    public SegDetAcciones() {
        super();
    }

    public SegDetAcciones(SegDetAccionesId id, SegDetNovedad segDetNovedad) {
        this.id = id;
        this.segDetNovedad = segDetNovedad;
    }

    public SegDetAcciones(SegDetAccionesId id, SegDetNovedad segDetNovedad, BigDecimal NCodAccion, BigDecimal NCodNovedad, BigDecimal NCodEmpresa, String VDescripcion, Date DFecHora, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion) {
        this.id = id;
        this.segDetNovedad = segDetNovedad;
        this.NCodAccion = NCodAccion;
        this.NCodNovedad = NCodNovedad;
        this.NCodEmpresa = NCodEmpresa;
        this.VDescripcion = VDescripcion;
        this.DFecHora = DFecHora;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
    }

    public SegDetAccionesId getId() {
        return this.id;
    }

    public void setId(SegDetAccionesId id) {
        this.id = id;
    }

    public SegDetNovedad getSegDetNovedad() {
        return this.segDetNovedad;
    }

    public void setSegDetNovedad(SegDetNovedad segDetNovedad) {
        this.segDetNovedad = segDetNovedad;
    }

    public BigDecimal getNCodAccion() {
        return NCodAccion;
    }

    public void setNCodAccion(BigDecimal NCodAccion) {
        this.NCodAccion = NCodAccion;
    }

    public BigDecimal getNCodNovedad() {
        return NCodNovedad;
    }

    public void setNCodNovedad(BigDecimal NCodNovedad) {
        this.NCodNovedad = NCodNovedad;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public Date getDFecHora() {
        return this.DFecHora;
    }

    public void setDFecHora(Date DFecHora) {
        this.DFecHora = DFecHora;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }
}
