package pe.com.segrop.sgsapp.domain;
// Generated 08-abr-2012 18:19:08 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetNovEvaluacionId generated by hbm2java
 */
public class SegDetNovEvaluacionId implements java.io.Serializable {

    private BigDecimal NCodEvaluacion;
    private BigDecimal NCodNovedad;
    private BigDecimal NCodEmpresa;

    public SegDetNovEvaluacionId() {
        super();
    }

    public SegDetNovEvaluacionId(BigDecimal NCodEvaluacion, BigDecimal NCodNovedad, BigDecimal NCodEmpresa) {
        this.NCodEvaluacion = NCodEvaluacion;
        this.NCodNovedad = NCodNovedad;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodEvaluacion() {
        return this.NCodEvaluacion;
    }

    public void setNCodEvaluacion(BigDecimal NCodEvaluacion) {
        this.NCodEvaluacion = NCodEvaluacion;
    }

    public BigDecimal getNCodNovedad() {
        return this.NCodNovedad;
    }

    public void setNCodNovedad(BigDecimal NCodNovedad) {
        this.NCodNovedad = NCodNovedad;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetNovEvaluacionId)) {
            return false;
        }
        SegDetNovEvaluacionId castOther = (SegDetNovEvaluacionId) other;

        return ((this.getNCodEvaluacion() == castOther.getNCodEvaluacion()) || (this.getNCodEvaluacion() != null && castOther.getNCodEvaluacion() != null && this.getNCodEvaluacion().equals(castOther.getNCodEvaluacion())))
                && ((this.getNCodNovedad() == castOther.getNCodNovedad()) || (this.getNCodNovedad() != null && castOther.getNCodNovedad() != null && this.getNCodNovedad().equals(castOther.getNCodNovedad())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodEvaluacion() == null ? 0 : this.getNCodEvaluacion().hashCode());
        result = 37 * result + (getNCodNovedad() == null ? 0 : this.getNCodNovedad().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
