package pe.com.segrop.sgsapp.domain;
// Generated 27-mar-2012 23:44:26 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetPreguntaId generated by hbm2java
 */
public class SegDetPreguntaId implements java.io.Serializable {

    private BigDecimal NCodEmpresa;
    private BigDecimal NCodPregunta;

    public SegDetPreguntaId() {
        super();
    }

    public SegDetPreguntaId(BigDecimal NCodEmpresa, BigDecimal NCodPregunta) {
        this.NCodEmpresa = NCodEmpresa;
        this.NCodPregunta = NCodPregunta;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodPregunta() {
        return this.NCodPregunta;
    }

    public void setNCodPregunta(BigDecimal NCodPregunta) {
        this.NCodPregunta = NCodPregunta;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetPreguntaId)) {
            return false;
        }
        SegDetPreguntaId castOther = (SegDetPreguntaId) other;

        return ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())))
                && ((this.getNCodPregunta() == castOther.getNCodPregunta()) || (this.getNCodPregunta() != null && castOther.getNCodPregunta() != null && this.getNCodPregunta().equals(castOther.getNCodPregunta())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        result = 37 * result + (getNCodPregunta() == null ? 0 : this.getNCodPregunta().hashCode());
        return result;
    }
}
