package pe.com.segrop.sgsapp.domain;
// Generated 13-mar-2012 2:47:19 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * SegDetInspreEvaluacion generated by hbm2java
 */
public class SegDetInspreEvaluacion implements java.io.Serializable {

    private SegDetInspreEvaluacionId id;
    private SegDetInsPresencial segDetInsPresencial;
    private BigDecimal NCodEvaluacion;
    private BigDecimal NCodInspresencial;
    private BigDecimal NCodEmpresa;
    private BigDecimal NOcurrencia;
    private BigDecimal NImpacto;
    private BigDecimal NEstado;
    private BigDecimal NNivelOcurrencia;
    private BigDecimal NNivelImpacto;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private List<SegDetInspreevalDetalle> segDetInspreevalDetalles = new ArrayList<SegDetInspreevalDetalle>(0);

    public SegDetInspreEvaluacion() {
        super();
    }

    public SegDetInspreEvaluacion(SegDetInspreEvaluacionId id, SegDetInsPresencial segDetInsPresencial) {
        this.id = id;
        this.segDetInsPresencial = segDetInsPresencial;
    }

    public SegDetInspreEvaluacion(SegDetInspreEvaluacionId id, SegDetInsPresencial segDetInsPresencial, BigDecimal NCodEvaluacion, BigDecimal NCodInspresencial, BigDecimal NCodEmpresa, BigDecimal NOcurrencia, BigDecimal NImpacto, BigDecimal NEstado, BigDecimal NNivelOcurrencia, BigDecimal NNivelImpacto, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, List<SegDetInspreevalDetalle> segDetInspreevalDetalles) {
        this.id = id;
        this.segDetInsPresencial = segDetInsPresencial;
        this.NCodEvaluacion = NCodEvaluacion;
        this.NCodInspresencial = NCodInspresencial;
        this.NCodEmpresa = NCodEmpresa;
        this.NOcurrencia = NOcurrencia;
        this.NImpacto = NImpacto;
        this.NEstado = NEstado;
        this.NNivelOcurrencia = NNivelOcurrencia;
        this.NNivelImpacto = NNivelImpacto;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.segDetInspreevalDetalles = segDetInspreevalDetalles;
    }

    public SegDetInspreEvaluacionId getId() {
        return this.id;
    }

    public void setId(SegDetInspreEvaluacionId id) {
        this.id = id;
    }

    public SegDetInsPresencial getSegDetInsPresencial() {
        return this.segDetInsPresencial;
    }

    public void setSegDetInsPresencial(SegDetInsPresencial segDetInsPresencial) {
        this.segDetInsPresencial = segDetInsPresencial;
    }

    public BigDecimal getNCodEvaluacion() {
        return NCodEvaluacion;
    }

    public void setNCodEvaluacion(BigDecimal NCodEvaluacion) {
        this.NCodEvaluacion = NCodEvaluacion;
    }

    public BigDecimal getNCodInspresencial() {
        return NCodInspresencial;
    }

    public void setNCodInspresencial(BigDecimal NCodInspresencial) {
        this.NCodInspresencial = NCodInspresencial;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNOcurrencia() {
        return NOcurrencia;
    }

    public void setNOcurrencia(BigDecimal NOcurrencia) {
        this.NOcurrencia = NOcurrencia;
    }

    public BigDecimal getNImpacto() {
        return NImpacto;
    }

    public void setNImpacto(BigDecimal NImpacto) {
        this.NImpacto = NImpacto;
    }

    public BigDecimal getNEstado() {
        return NEstado;
    }

    public void setNEstado(BigDecimal NEstado) {
        this.NEstado = NEstado;
    }

    public BigDecimal getNNivelOcurrencia() {
        return NNivelOcurrencia;
    }

    public void setNNivelOcurrencia(BigDecimal NNivelOcurrencia) {
        this.NNivelOcurrencia = NNivelOcurrencia;
    }

    public BigDecimal getNNivelImpacto() {
        return NNivelImpacto;
    }

    public void setNNivelImpacto(BigDecimal NNivelImpacto) {
        this.NNivelImpacto = NNivelImpacto;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public List<SegDetInspreevalDetalle> getSegDetInspreevalDetalles() {
        return segDetInspreevalDetalles;
    }

    public void setSegDetInspreevalDetalles(List<SegDetInspreevalDetalle> segDetInspreevalDetalles) {
        this.segDetInspreevalDetalles = segDetInspreevalDetalles;
    }
}
