package pe.com.segrop.sgsapp.domain;
// Generated 27-mar-2012 23:44:26 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * SegDetPregunta generated by hbm2java
 */
public class SegDetPregunta implements java.io.Serializable {

    private SegDetPreguntaId id;
    private BigDecimal NCodEmpresa;
    private BigDecimal NCodPregunta;
    private String VDescripcion;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private String VIpModificacion;
    private Date DFecModificacion;
    private Set<SegDetInsTelefonica> segDetInsTelefonicas = new HashSet<SegDetInsTelefonica>(0);
    private List<SegDetRespuesta> segDetRespuestas = new ArrayList<SegDetRespuesta>(0);
    private String VRespuesta;

    public SegDetPregunta() {
        super();
    }

    public SegDetPregunta(SegDetPreguntaId id) {
        this.id = id;
    }

    public SegDetPregunta(SegDetPreguntaId id, BigDecimal NCodEmpresa, BigDecimal NCodPregunta, String VDescripcion, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, String VIpModificacion, Date DFecModificacion, Set<SegDetInsTelefonica> segDetInsTelefonicas) {
        this.id = id;
        this.NCodEmpresa = NCodEmpresa;
        this.NCodPregunta = NCodPregunta;
        this.VDescripcion = VDescripcion;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.VIpModificacion = VIpModificacion;
        this.DFecModificacion = DFecModificacion;
        this.segDetInsTelefonicas = segDetInsTelefonicas;
    }

    public SegDetPreguntaId getId() {
        return this.id;
    }

    public void setId(SegDetPreguntaId id) {
        this.id = id;
    }

    /**
     * @return the NCodEmpresa
     */
    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    /**
     * @param NCodEmpresa the NCodEmpresa to set
     */
    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    /**
     * @return the NCodPregunta
     */
    public BigDecimal getNCodPregunta() {
        return NCodPregunta;
    }

    /**
     * @param NCodPregunta the NCodPregunta to set
     */
    public void setNCodPregunta(BigDecimal NCodPregunta) {
        this.NCodPregunta = NCodPregunta;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public Set<SegDetInsTelefonica> getSegDetInsTelefonicas() {
        return this.segDetInsTelefonicas;
    }

    public void setSegDetInsTelefonicas(Set<SegDetInsTelefonica> segDetInsTelefonicas) {
        this.segDetInsTelefonicas = segDetInsTelefonicas;
    }

    public List<SegDetRespuesta> getSegDetRespuestas() {
        return segDetRespuestas;
    }

    public void setSegDetRespuestas(List<SegDetRespuesta> segDetRespuestas) {
        this.segDetRespuestas = segDetRespuestas;
    }

    public String getVRespuesta() {
        return VRespuesta;
    }

    public void setVRespuesta(String VRespuesta) {
        this.VRespuesta = VRespuesta;
    }
}
