package pe.com.segrop.sgsapp.domain;
// Generated 21-feb-2012 0:26:46 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetLugarId generated by hbm2java
 */
public class SegDetLugarId implements java.io.Serializable {

    private BigDecimal NCodLugar;
    private BigDecimal NCodArea;
    private BigDecimal NCodLocal;
    private BigDecimal NCodEmpresa;

    public SegDetLugarId() {
        super();
    }

    public SegDetLugarId(BigDecimal NCodLugar, BigDecimal NCodArea, BigDecimal NCodLocal, BigDecimal NCodEmpresa) {
        this.NCodLugar = NCodLugar;
        this.NCodArea = NCodArea;
        this.NCodLocal = NCodLocal;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodLugar() {
        return this.NCodLugar;
    }

    public void setNCodLugar(BigDecimal NCodLugar) {
        this.NCodLugar = NCodLugar;
    }

    public BigDecimal getNCodArea() {
        return this.NCodArea;
    }

    public void setNCodArea(BigDecimal NCodArea) {
        this.NCodArea = NCodArea;
    }

    public BigDecimal getNCodLocal() {
        return this.NCodLocal;
    }

    public void setNCodLocal(BigDecimal NCodLocal) {
        this.NCodLocal = NCodLocal;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetLugarId)) {
            return false;
        }
        SegDetLugarId castOther = (SegDetLugarId) other;

        return ((this.getNCodLugar() == castOther.getNCodLugar()) || (this.getNCodLugar() != null && castOther.getNCodLugar() != null && this.getNCodLugar().equals(castOther.getNCodLugar())))
                && ((this.getNCodArea() == castOther.getNCodArea()) || (this.getNCodArea() != null && castOther.getNCodArea() != null && this.getNCodArea().equals(castOther.getNCodArea())))
                && ((this.getNCodLocal() == castOther.getNCodLocal()) || (this.getNCodLocal() != null && castOther.getNCodLocal() != null && this.getNCodLocal().equals(castOther.getNCodLocal())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodLugar() == null ? 0 : this.getNCodLugar().hashCode());
        result = 37 * result + (getNCodArea() == null ? 0 : this.getNCodArea().hashCode());
        result = 37 * result + (getNCodLocal() == null ? 0 : this.getNCodLocal().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
