package pe.com.segrop.sgsapp.domain;
// Generated 27-mar-2012 23:44:26 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SegDetRespuesta generated by hbm2java
 */
public class SegDetRespuesta implements java.io.Serializable {

    private SegDetRespuestaId id;
    private SegRelCuestionario segRelCuestionario;
    private BigDecimal NCodRespuesta;
    private BigDecimal NCodEmpresa;
    private BigDecimal NCodPregunta;
    private BigDecimal NCodInstelefonica;
    private String VDescripcion;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;

    public SegDetRespuesta() {
        super();
    }

    public SegDetRespuesta(SegDetRespuestaId id, SegRelCuestionario segRelCuestionario, BigDecimal NCodRespuesta, BigDecimal NCodEmpresa, BigDecimal NCodPregunta, BigDecimal NCodInstelefonica) {
        this.id = id;
        this.segRelCuestionario = segRelCuestionario;
        this.NCodRespuesta = NCodRespuesta;
        this.NCodEmpresa = NCodEmpresa;
        this.NCodPregunta = NCodPregunta;
        this.NCodInstelefonica = NCodInstelefonica;
    }

    public SegDetRespuesta(SegDetRespuestaId id, SegRelCuestionario segRelCuestionario, BigDecimal NCodRespuesta, BigDecimal NCodEmpresa, BigDecimal NCodPregunta, BigDecimal NCodInstelefonica, String VDescripcion, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion) {
        this.id = id;
        this.segRelCuestionario = segRelCuestionario;
        this.NCodRespuesta = NCodRespuesta;
        this.NCodEmpresa = NCodEmpresa;
        this.NCodPregunta = NCodPregunta;
        this.NCodInstelefonica = NCodInstelefonica;
        this.VDescripcion = VDescripcion;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
    }

    public SegDetRespuestaId getId() {
        return this.id;
    }

    public void setId(SegDetRespuestaId id) {
        this.id = id;
    }

    public SegRelCuestionario getSegRelCuestionario() {
        return this.segRelCuestionario;
    }

    public void setSegRelCuestionario(SegRelCuestionario segRelCuestionario) {
        this.segRelCuestionario = segRelCuestionario;
    }

    public BigDecimal getNCodRespuesta() {
        return NCodRespuesta;
    }

    public void setNCodRespuesta(BigDecimal NCodRespuesta) {
        this.NCodRespuesta = NCodRespuesta;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodPregunta() {
        return NCodPregunta;
    }

    public void setNCodPregunta(BigDecimal NCodPregunta) {
        this.NCodPregunta = NCodPregunta;
    }

    public BigDecimal getNCodInstelefonica() {
        return NCodInstelefonica;
    }

    public void setNCodInstelefonica(BigDecimal NCodInstelefonica) {
        this.NCodInstelefonica = NCodInstelefonica;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }
}
