package pe.com.segrop.sgsapp.domain;
// Generated 16-mar-2012 0:40:39 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegDetObjeto generated by hbm2java
 */
public class SegDetObjeto implements java.io.Serializable {

    private BigDecimal NCodObjeto;
    private String VNombre;
    private String VDescripcion;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private Set<SegDetPerfil> segDetPerfils = new HashSet<SegDetPerfil>(0);

    public SegDetObjeto() {
        super();
    }

    public SegDetObjeto(BigDecimal NCodObjeto) {
        this.NCodObjeto = NCodObjeto;
    }

    public SegDetObjeto(BigDecimal NCodObjeto, String VNombre, String VDescripcion, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, Set<SegDetPerfil> segDetPerfils) {
        this.NCodObjeto = NCodObjeto;
        this.VNombre = VNombre;
        this.VDescripcion = VDescripcion;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.segDetPerfils = segDetPerfils;
    }

    public BigDecimal getNCodObjeto() {
        return this.NCodObjeto;
    }

    public void setNCodObjeto(BigDecimal NCodObjeto) {
        this.NCodObjeto = NCodObjeto;
    }

    public String getVNombre() {
        return this.VNombre;
    }

    public void setVNombre(String VNombre) {
        this.VNombre = VNombre;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Set<SegDetPerfil> getSegDetPerfils() {
        return this.segDetPerfils;
    }

    public void setSegDetPerfils(Set<SegDetPerfil> segDetPerfils) {
        this.segDetPerfils = segDetPerfils;
    }
}
