package pe.com.segrop.sgsapp.domain;
// Generated 27-may-2012 20:47:48 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegDetCapacitacion generated by hbm2java
 */
public class SegDetCapacitacion implements java.io.Serializable {

    private SegDetCapacitacionId id;
    private BigDecimal NCodEmpresa;
    private BigDecimal NCodCapacitacion;
    private String VNombre;
    private String VDescripcion;
    private BigDecimal NLugar;
    private BigDecimal NModalidad;
    private BigDecimal NTipoCapacitacion;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private Date DFechaHora;
    private Date DFecInicio;
    private Date DFecFin;
    private Set<SegDetParticipante> segDetParticipantes = new HashSet<SegDetParticipante>(0);

    public SegDetCapacitacion() {
        super();
    }

    public SegDetCapacitacion(SegDetCapacitacionId id, BigDecimal NCodEmpresa, BigDecimal NCodCapacitacion) {
        this.id = id;
        this.NCodEmpresa = NCodEmpresa;
        this.NCodCapacitacion = NCodCapacitacion;
    }

    public SegDetCapacitacion(SegDetCapacitacionId id, BigDecimal NCodEmpresa, BigDecimal NCodCapacitacion, String VNombre, String VDescripcion, BigDecimal NLugar, BigDecimal NModalidad, BigDecimal NTipoCapacitacion, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, Date DFechaHora, Set<SegDetParticipante> segDetParticipantes) {
        this.id = id;
        this.NCodEmpresa = NCodEmpresa;
        this.NCodCapacitacion = NCodCapacitacion;
        this.VNombre = VNombre;
        this.VDescripcion = VDescripcion;
        this.NLugar = NLugar;
        this.NModalidad = NModalidad;
        this.NTipoCapacitacion = NTipoCapacitacion;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.DFechaHora = DFechaHora;
        this.segDetParticipantes = segDetParticipantes;
    }

    public SegDetCapacitacionId getId() {
        return this.id;
    }

    public void setId(SegDetCapacitacionId id) {
        this.id = id;
    }

    /**
     * @return the NCodEmpresa
     */
    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    /**
     * @param NCodEmpresa the NCodEmpresa to set
     */
    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    /**
     * @return the NCodCapacitacion
     */
    public BigDecimal getNCodCapacitacion() {
        return NCodCapacitacion;
    }

    /**
     * @param NCodCapacitacion the NCodCapacitacion to set
     */
    public void setNCodCapacitacion(BigDecimal NCodCapacitacion) {
        this.NCodCapacitacion = NCodCapacitacion;
    }

    public String getVNombre() {
        return this.VNombre;
    }

    public void setVNombre(String VNombre) {
        this.VNombre = VNombre;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public BigDecimal getNLugar() {
        return this.NLugar;
    }

    public void setNLugar(BigDecimal NLugar) {
        this.NLugar = NLugar;
    }

    public BigDecimal getNModalidad() {
        return this.NModalidad;
    }

    public void setNModalidad(BigDecimal NModalidad) {
        this.NModalidad = NModalidad;
    }

    public BigDecimal getNTipoCapacitacion() {
        return this.NTipoCapacitacion;
    }

    public void setNTipoCapacitacion(BigDecimal NTipoCapacitacion) {
        this.NTipoCapacitacion = NTipoCapacitacion;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Date getDFechaHora() {
        return this.DFechaHora;
    }

    public void setDFechaHora(Date DFechaHora) {
        this.DFechaHora = DFechaHora;
    }

    /**
     * @return the DFecInicio
     */
    public Date getDFecInicio() {
        return DFecInicio;
    }

    /**
     * @param DFecInicio the DFecInicio to set
     */
    public void setDFecInicio(Date DFecInicio) {
        this.DFecInicio = DFecInicio;
    }

    /**
     * @return the DFecFin
     */
    public Date getDFecFin() {
        return DFecFin;
    }

    /**
     * @param DFecFin the DFecFin to set
     */
    public void setDFecFin(Date DFecFin) {
        this.DFecFin = DFecFin;
    }

    public Set<SegDetParticipante> getSegDetParticipantes() {
        return this.segDetParticipantes;
    }

    public void setSegDetParticipantes(Set<SegDetParticipante> segDetParticipantes) {
        this.segDetParticipantes = segDetParticipantes;
    }
}
