package pe.com.segrop.sgsapp.domain;
// Generated 16-mar-2012 0:40:39 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegDetPerfil generated by hbm2java
 */
public class SegDetPerfil implements java.io.Serializable {

    private SegDetPerfilId id;
    private BigDecimal NCodPerfil;
    private BigDecimal NCodEmpresa;
    private String VDescripcion;
    private String VNombre;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private Set<SegRelUsuarioperfil> segRelUsuarioperfils = new HashSet<SegRelUsuarioperfil>(0);
    private Set<SegRelPermiso> segRelPermisos = new HashSet<SegRelPermiso>(0);
    private Set<SegDetObjeto> segDetObjetos = new HashSet<SegDetObjeto>(0);

    public SegDetPerfil() {
        super();
    }

    public SegDetPerfil(SegDetPerfilId id) {
        this.id = id;
    }

    public SegDetPerfil(SegDetPerfilId id, BigDecimal NCodPerfil, BigDecimal NCodEmpresa, String VDescripcion, String VNombre, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, Set<SegRelUsuarioperfil> segRelUsuarioperfils, Set<SegDetObjeto> segDetObjetos) {
        this.id = id;
        this.NCodPerfil = NCodPerfil;
        this.NCodEmpresa = NCodEmpresa;
        this.VDescripcion = VDescripcion;
        this.VNombre = VNombre;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.segRelUsuarioperfils = segRelUsuarioperfils;
        this.segDetObjetos = segDetObjetos;
    }

    public SegDetPerfilId getId() {
        return this.id;
    }

    public void setId(SegDetPerfilId id) {
        this.id = id;
    }

    public BigDecimal getNCodPerfil() {
        return NCodPerfil;
    }

    public void setNCodPerfil(BigDecimal NCodPerfil) {
        this.NCodPerfil = NCodPerfil;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public String getVNombre() {
        return this.VNombre;
    }

    public void setVNombre(String VNombre) {
        this.VNombre = VNombre;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public Set<SegRelUsuarioperfil> getSegRelUsuarioperfils() {
        return this.segRelUsuarioperfils;
    }

    public void setSegRelUsuarioperfils(Set<SegRelUsuarioperfil> segRelUsuarioperfils) {
        this.segRelUsuarioperfils = segRelUsuarioperfils;
    }

    public Set<SegRelPermiso> getSegRelPermisos() {
        return segRelPermisos;
    }

    public void setSegRelPermisos(Set<SegRelPermiso> segRelPermisos) {
        this.segRelPermisos = segRelPermisos;
    }

    public Set<SegDetObjeto> getSegDetObjetos() {
        return this.segDetObjetos;
    }

    public void setSegDetObjetos(Set<SegDetObjeto> segDetObjetos) {
        this.segDetObjetos = segDetObjetos;
    }
}
