package pe.com.segrop.sgsapp.domain;
// Generated 11-mar-2012 1:13:03 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SegDetHistorial generated by hbm2java
 */
public class SegDetHistorial implements java.io.Serializable {

    private SegDetHistorialId id;
    private SegDetDocumento segDetDocumento;
    private BigDecimal NCodHistorial;
    private BigDecimal NCodDocumento;
    private BigDecimal NCodEmpresa;
    private BigDecimal NProcedencia;
    private BigDecimal NTipoDocumento;
    private Date DFecEmision;
    private String VDescripcion;
    private String VNombre;
    private String VRuta;
    private BigDecimal NVersion;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private String VNombreOriginal;

    public SegDetHistorial() {
        super();
    }

    public SegDetHistorial(SegDetHistorialId id, SegDetDocumento segDetDocumento) {
        this.id = id;
        this.segDetDocumento = segDetDocumento;
    }

    public SegDetHistorial(SegDetHistorialId id, SegDetDocumento segDetDocumento, BigDecimal NCodHistorial, BigDecimal NCodDocumento, BigDecimal NCodEmpresa, BigDecimal NProcedencia, BigDecimal NTipoDocumento, Date DFecEmision, String VDescripcion, String VNombre, String VRuta, BigDecimal NVersion, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, String VNombreOriginal) {
        this.id = id;
        this.segDetDocumento = segDetDocumento;
        this.NCodHistorial = NCodHistorial;
        this.NCodDocumento = NCodDocumento;
        this.NCodEmpresa = NCodEmpresa;
        this.NProcedencia = NProcedencia;
        this.NTipoDocumento = NTipoDocumento;
        this.DFecEmision = DFecEmision;
        this.VDescripcion = VDescripcion;
        this.VNombre = VNombre;
        this.VRuta = VRuta;
        this.NVersion = NVersion;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.VNombreOriginal = VNombreOriginal;
    }

    public SegDetHistorialId getId() {
        return this.id;
    }

    public void setId(SegDetHistorialId id) {
        this.id = id;
    }

    public SegDetDocumento getSegDetDocumento() {
        return this.segDetDocumento;
    }

    public void setSegDetDocumento(SegDetDocumento segDetDocumento) {
        this.segDetDocumento = segDetDocumento;
    }

    public BigDecimal getNCodHistorial() {
        return NCodHistorial;
    }

    public void setNCodHistorial(BigDecimal NCodHistorial) {
        this.NCodHistorial = NCodHistorial;
    }

    public BigDecimal getNCodDocumento() {
        return NCodDocumento;
    }

    public void setNCodDocumento(BigDecimal NCodDocumento) {
        this.NCodDocumento = NCodDocumento;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNProcedencia() {
        return this.NProcedencia;
    }

    public void setNProcedencia(BigDecimal NProcedencia) {
        this.NProcedencia = NProcedencia;
    }

    public BigDecimal getNTipoDocumento() {
        return this.NTipoDocumento;
    }

    public void setNTipoDocumento(BigDecimal NTipoDocumento) {
        this.NTipoDocumento = NTipoDocumento;
    }

    public Date getDFecEmision() {
        return this.DFecEmision;
    }

    public void setDFecEmision(Date DFecEmision) {
        this.DFecEmision = DFecEmision;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public String getVNombre() {
        return this.VNombre;
    }

    public void setVNombre(String VNombre) {
        this.VNombre = VNombre;
    }

    public String getVRuta() {
        return this.VRuta;
    }

    public void setVRuta(String VRuta) {
        this.VRuta = VRuta;
    }

    public BigDecimal getNVersion() {
        return this.NVersion;
    }

    public void setNVersion(BigDecimal NVersion) {
        this.NVersion = NVersion;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public String getVNombreOriginal() {
        return this.VNombreOriginal;
    }

    public void setVNombreOriginal(String VNombreOriginal) {
        this.VNombreOriginal = VNombreOriginal;
    }
}
