package pe.com.segrop.sgsapp.domain;
// Generated 11-mar-2012 1:13:03 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SegDetDocumento generated by hbm2java
 */
public class SegDetDocumento implements java.io.Serializable {

    private SegDetDocumentoId id;
    private BigDecimal NCodDocumento;
    private BigDecimal NCodEmpresa;
    private BigDecimal NProcedencia;
    private BigDecimal NTipoDocumento;
    private Date DFecEmision;
    private String VDescripcion;
    private String VNombre;
    private String VRuta;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;
    private BigDecimal NVersion;
    private String VNombreOriginal;
    private BigDecimal NActivo;
    private Date DFecInicio;
    private Date DFecFin;
    private Set<SegDetHistorial> segDetHistorials = new HashSet<SegDetHistorial>(0);

    public SegDetDocumento() {
        super();
    }

    public SegDetDocumento(SegDetDocumentoId id) {
        this.id = id;
    }

    public SegDetDocumento(SegDetDocumentoId id, BigDecimal NCodDocumento, BigDecimal NCodEmpresa, BigDecimal NProcedencia, BigDecimal NTipoDocumento, Date DFecEmision, String VDescripcion, String VNombre, String VRuta, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion, BigDecimal NVersion, String VNombreOriginal, BigDecimal NActivo, Date DFecInicio, Date DFecFin, Set<SegDetHistorial> segDetHistorials) {
        this.id = id;
        this.NCodDocumento = NCodDocumento;
        this.NCodEmpresa = NCodEmpresa;
        this.NProcedencia = NProcedencia;
        this.NTipoDocumento = NTipoDocumento;
        this.DFecEmision = DFecEmision;
        this.VDescripcion = VDescripcion;
        this.VNombre = VNombre;
        this.VRuta = VRuta;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
        this.NVersion = NVersion;
        this.VNombreOriginal = VNombreOriginal;
        this.NActivo = NActivo;
        this.DFecInicio = DFecInicio;
        this.DFecFin = DFecFin;
        this.segDetHistorials = segDetHistorials;
    }

    public SegDetDocumentoId getId() {
        return this.id;
    }

    public void setId(SegDetDocumentoId id) {
        this.id = id;
    }

    public BigDecimal getNCodDocumento() {
        return NCodDocumento;
    }

    public void setNCodDocumento(BigDecimal NCodDocumento) {
        this.NCodDocumento = NCodDocumento;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNProcedencia() {
        return this.NProcedencia;
    }

    public void setNProcedencia(BigDecimal NProcedencia) {
        this.NProcedencia = NProcedencia;
    }

    public BigDecimal getNTipoDocumento() {
        return this.NTipoDocumento;
    }

    public void setNTipoDocumento(BigDecimal NTipoDocumento) {
        this.NTipoDocumento = NTipoDocumento;
    }

    public Date getDFecEmision() {
        return this.DFecEmision;
    }

    public void setDFecEmision(Date DFecEmision) {
        this.DFecEmision = DFecEmision;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public String getVNombre() {
        return this.VNombre;
    }

    public void setVNombre(String VNombre) {
        this.VNombre = VNombre;
    }

    public String getVRuta() {
        return this.VRuta;
    }

    public void setVRuta(String VRuta) {
        this.VRuta = VRuta;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }

    public BigDecimal getNVersion() {
        return this.NVersion;
    }

    public void setNVersion(BigDecimal NVersion) {
        this.NVersion = NVersion;
    }

    public String getVNombreOriginal() {
        return this.VNombreOriginal;
    }

    public void setVNombreOriginal(String VNombreOriginal) {
        this.VNombreOriginal = VNombreOriginal;
    }

    public BigDecimal getNActivo() {
        return NActivo;
    }

    public void setNActivo(BigDecimal NActivo) {
        this.NActivo = NActivo;
    }

    public Date getDFecInicio() {
        return DFecInicio;
    }

    public void setDFecInicio(Date DFecInicio) {
        this.DFecInicio = DFecInicio;
    }

    public Date getDFecFin() {
        return DFecFin;
    }

    public void setDFecFin(Date DFecFin) {
        this.DFecFin = DFecFin;
    }

    public Set<SegDetHistorial> getSegDetHistorials() {
        return this.segDetHistorials;
    }

    public void setSegDetHistorials(Set<SegDetHistorial> segDetHistorials) {
        this.segDetHistorials = segDetHistorials;
    }
}
