package pe.com.segrop.sgsapp.domain;
// Generated 21-feb-2012 0:26:46 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SegDetResponsable generated by hbm2java
 */
public class SegDetResponsable implements java.io.Serializable {

    private SegDetResponsableId id;
    private SegDetArea segDetArea;
    private BigDecimal NCodResponsable;
    private BigDecimal NCodArea;
    private BigDecimal NCodLocal;
    private BigDecimal NCodEmpresa;
    private String VNombres;
    private String VApellidos;
    private String VNombrecompleto;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;

    public SegDetResponsable() {
        super();
    }

    public SegDetResponsable(SegDetResponsableId id, SegDetArea segDetArea) {
        this.id = id;
        this.segDetArea = segDetArea;
    }

    public SegDetResponsable(SegDetResponsableId id, SegDetArea segDetArea, BigDecimal NCodResponsable, BigDecimal NCodArea, BigDecimal NCodLocal, BigDecimal NCodEmpresa, String VNombres, String VApellidos, String VNombrecompleto, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion) {
        this.id = id;
        this.segDetArea = segDetArea;
        this.NCodResponsable = NCodResponsable;
        this.NCodArea = NCodArea;
        this.NCodLocal = NCodLocal;
        this.NCodEmpresa = NCodEmpresa;
        this.VNombres = VNombres;
        this.VApellidos = VApellidos;
        this.VNombrecompleto = VNombrecompleto;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
    }

    public SegDetResponsableId getId() {
        return this.id;
    }

    public void setId(SegDetResponsableId id) {
        this.id = id;
    }

    public SegDetArea getSegDetArea() {
        return this.segDetArea;
    }

    public void setSegDetArea(SegDetArea segDetArea) {
        this.segDetArea = segDetArea;
    }

    public BigDecimal getNCodResponsable() {
        return NCodResponsable;
    }

    public void setNCodResponsable(BigDecimal NCodResponsable) {
        this.NCodResponsable = NCodResponsable;
    }

    public BigDecimal getNCodArea() {
        return NCodArea;
    }

    public void setNCodArea(BigDecimal NCodArea) {
        this.NCodArea = NCodArea;
    }

    public BigDecimal getNCodLocal() {
        return NCodLocal;
    }

    public void setNCodLocal(BigDecimal NCodLocal) {
        this.NCodLocal = NCodLocal;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public String getVNombres() {
        return this.VNombres;
    }

    public void setVNombres(String VNombres) {
        this.VNombres = VNombres;
    }

    public String getVApellidos() {
        return this.VApellidos;
    }

    public void setVApellidos(String VApellidos) {
        this.VApellidos = VApellidos;
    }

    public String getVNombrecompleto() {
        return VNombrecompleto;
    }

    public void setVNombrecompleto(String VNombrecompleto) {
        this.VNombrecompleto = VNombrecompleto;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }
}
