package pe.com.segrop.sgsapp.domain;
// Generated 29-abr-2012 21:05:00 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetRiesgoId generated by hbm2java
 */
public class SegDetRiesgoId implements java.io.Serializable {

    private BigDecimal NCodEmpresa;
    private BigDecimal NCodRiesgo;
    private BigDecimal NTipoRiesgo;

    public SegDetRiesgoId() {
        super();
    }

    public SegDetRiesgoId(BigDecimal NCodEmpresa, BigDecimal NCodRiesgo, BigDecimal NTipoRiesgo) {
        this.NCodEmpresa = NCodEmpresa;
        this.NCodRiesgo = NCodRiesgo;
        this.NTipoRiesgo = NTipoRiesgo;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodRiesgo() {
        return this.NCodRiesgo;
    }

    public void setNCodRiesgo(BigDecimal NCodRiesgo) {
        this.NCodRiesgo = NCodRiesgo;
    }

    public BigDecimal getNTipoRiesgo() {
        return this.NTipoRiesgo;
    }

    public void setNTipoRiesgo(BigDecimal NTipoRiesgo) {
        this.NTipoRiesgo = NTipoRiesgo;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetRiesgoId)) {
            return false;
        }
        SegDetRiesgoId castOther = (SegDetRiesgoId) other;

        return ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())))
                && ((this.getNCodRiesgo() == castOther.getNCodRiesgo()) || (this.getNCodRiesgo() != null && castOther.getNCodRiesgo() != null && this.getNCodRiesgo().equals(castOther.getNCodRiesgo())))
                && ((this.getNTipoRiesgo() == castOther.getNTipoRiesgo()) || (this.getNTipoRiesgo() != null && castOther.getNTipoRiesgo() != null && this.getNTipoRiesgo().equals(castOther.getNTipoRiesgo())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        result = 37 * result + (getNCodRiesgo() == null ? 0 : this.getNCodRiesgo().hashCode());
        result = 37 * result + (getNTipoRiesgo() == null ? 0 : this.getNTipoRiesgo().hashCode());
        return result;
    }
}
