package pe.com.segrop.sgsapp.domain;
// Generated 27-may-2012 20:47:48 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetParticipanteId generated by hbm2java
 */
public class SegDetParticipanteId implements java.io.Serializable {

    private BigDecimal NCodEmpresa;
    private BigDecimal NCodCapacitacion;
    private BigDecimal NCodParticipante;

    public SegDetParticipanteId() {
        super();
    }

    public SegDetParticipanteId(BigDecimal NCodEmpresa, BigDecimal NCodCapacitacion, BigDecimal NCodParticipante) {
        this.NCodEmpresa = NCodEmpresa;
        this.NCodCapacitacion = NCodCapacitacion;
        this.NCodParticipante = NCodParticipante;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodCapacitacion() {
        return this.NCodCapacitacion;
    }

    public void setNCodCapacitacion(BigDecimal NCodCapacitacion) {
        this.NCodCapacitacion = NCodCapacitacion;
    }

    public BigDecimal getNCodParticipante() {
        return this.NCodParticipante;
    }

    public void setNCodParticipante(BigDecimal NCodParticipante) {
        this.NCodParticipante = NCodParticipante;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetParticipanteId)) {
            return false;
        }
        SegDetParticipanteId castOther = (SegDetParticipanteId) other;

        return ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())))
                && ((this.getNCodCapacitacion() == castOther.getNCodCapacitacion()) || (this.getNCodCapacitacion() != null && castOther.getNCodCapacitacion() != null && this.getNCodCapacitacion().equals(castOther.getNCodCapacitacion())))
                && ((this.getNCodParticipante() == castOther.getNCodParticipante()) || (this.getNCodParticipante() != null && castOther.getNCodParticipante() != null && this.getNCodParticipante().equals(castOther.getNCodParticipante())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        result = 37 * result + (getNCodCapacitacion() == null ? 0 : this.getNCodCapacitacion().hashCode());
        result = 37 * result + (getNCodParticipante() == null ? 0 : this.getNCodParticipante().hashCode());
        return result;
    }
}
