package pe.com.segrop.sgsapp.domain;
// Generated 11-mar-2012 1:13:03 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetHistorialId generated by hbm2java
 */
public class SegDetHistorialId implements java.io.Serializable {

    private BigDecimal NCodHistorial;
    private BigDecimal NCodDocumento;
    private BigDecimal NCodEmpresa;

    public SegDetHistorialId() {
        super();
    }

    public SegDetHistorialId(BigDecimal NCodHistorial, BigDecimal NCodDocumento, BigDecimal NCodEmpresa) {
        this.NCodHistorial = NCodHistorial;
        this.NCodDocumento = NCodDocumento;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodHistorial() {
        return this.NCodHistorial;
    }

    public void setNCodHistorial(BigDecimal NCodHistorial) {
        this.NCodHistorial = NCodHistorial;
    }

    public BigDecimal getNCodDocumento() {
        return this.NCodDocumento;
    }

    public void setNCodDocumento(BigDecimal NCodDocumento) {
        this.NCodDocumento = NCodDocumento;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetHistorialId)) {
            return false;
        }
        SegDetHistorialId castOther = (SegDetHistorialId) other;

        return ((this.getNCodHistorial() == castOther.getNCodHistorial()) || (this.getNCodHistorial() != null && castOther.getNCodHistorial() != null && this.getNCodHistorial().equals(castOther.getNCodHistorial())))
                && ((this.getNCodDocumento() == castOther.getNCodDocumento()) || (this.getNCodDocumento() != null && castOther.getNCodDocumento() != null && this.getNCodDocumento().equals(castOther.getNCodDocumento())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodHistorial() == null ? 0 : this.getNCodHistorial().hashCode());
        result = 37 * result + (getNCodDocumento() == null ? 0 : this.getNCodDocumento().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
