package pe.com.segrop.sgsapp.domain;
// Generated 27-may-2012 20:47:48 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetCapacitacionId generated by hbm2java
 */
public class SegDetCapacitacionId implements java.io.Serializable {

    private BigDecimal NCodEmpresa;
    private BigDecimal NCodCapacitacion;

    public SegDetCapacitacionId() {
        super();
    }

    public SegDetCapacitacionId(BigDecimal NCodEmpresa, BigDecimal NCodCapacitacion) {
        this.NCodEmpresa = NCodEmpresa;
        this.NCodCapacitacion = NCodCapacitacion;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodCapacitacion() {
        return this.NCodCapacitacion;
    }

    public void setNCodCapacitacion(BigDecimal NCodCapacitacion) {
        this.NCodCapacitacion = NCodCapacitacion;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetCapacitacionId)) {
            return false;
        }
        SegDetCapacitacionId castOther = (SegDetCapacitacionId) other;

        return ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())))
                && ((this.getNCodCapacitacion() == castOther.getNCodCapacitacion()) || (this.getNCodCapacitacion() != null && castOther.getNCodCapacitacion() != null && this.getNCodCapacitacion().equals(castOther.getNCodCapacitacion())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        result = 37 * result + (getNCodCapacitacion() == null ? 0 : this.getNCodCapacitacion().hashCode());
        return result;
    }
}
