package pe.com.segrop.sgsapp.domain;
// Generated 13-mar-2012 2:47:19 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetInsPresencialId generated by hbm2java
 */
public class SegDetInsPresencialId implements java.io.Serializable {

    private BigDecimal NCodInspresencial;
    private BigDecimal NCodEmpresa;

    public SegDetInsPresencialId() {
        super();
    }

    public SegDetInsPresencialId(BigDecimal NCodInspresencial, BigDecimal NCodEmpresa) {
        this.NCodInspresencial = NCodInspresencial;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodInspresencial() {
        return this.NCodInspresencial;
    }

    public void setNCodInspresencial(BigDecimal NCodInspresencial) {
        this.NCodInspresencial = NCodInspresencial;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetInsPresencialId)) {
            return false;
        }
        SegDetInsPresencialId castOther = (SegDetInsPresencialId) other;

        return ((this.getNCodInspresencial() == castOther.getNCodInspresencial()) || (this.getNCodInspresencial() != null && castOther.getNCodInspresencial() != null && this.getNCodInspresencial().equals(castOther.getNCodInspresencial())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodInspresencial() == null ? 0 : this.getNCodInspresencial().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
