package pe.com.segrop.sgsapp.domain;
// Generated 21-feb-2012 0:26:46 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetTipoDocumentoId generated by hbm2java
 */
public class SegDetTipoDocumentoId implements java.io.Serializable {

    private BigDecimal NCodTipoDocumento;
    private BigDecimal NCodEmpresa;

    public SegDetTipoDocumentoId() {
        super();
    }

    public SegDetTipoDocumentoId(BigDecimal NCodTipoDocumento, BigDecimal NCodEmpresa) {
        this.NCodTipoDocumento = NCodTipoDocumento;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodTipoDocumento() {
        return this.NCodTipoDocumento;
    }

    public void setNCodTipoDocumento(BigDecimal NCodTipoDocumento) {
        this.NCodTipoDocumento = NCodTipoDocumento;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetTipoDocumentoId)) {
            return false;
        }
        SegDetTipoDocumentoId castOther = (SegDetTipoDocumentoId) other;

        return ((this.getNCodTipoDocumento() == castOther.getNCodTipoDocumento()) || (this.getNCodTipoDocumento() != null && castOther.getNCodTipoDocumento() != null && this.getNCodTipoDocumento().equals(castOther.getNCodTipoDocumento())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodTipoDocumento() == null ? 0 : this.getNCodTipoDocumento().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
