package pe.com.segrop.sgsapp.domain;
// Generated 13-mar-2012 2:47:19 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegDetInspreAccionesId generated by hbm2java
 */
public class SegDetInspreAccionesId implements java.io.Serializable {

    private BigDecimal NCodAccion;
    private BigDecimal NCodInspresencial;
    private BigDecimal NCodEmpresa;

    public SegDetInspreAccionesId() {
        super();
    }

    public SegDetInspreAccionesId(BigDecimal NCodAccion, BigDecimal NCodInspresencial, BigDecimal NCodEmpresa) {
        this.NCodAccion = NCodAccion;
        this.NCodInspresencial = NCodInspresencial;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodAccion() {
        return this.NCodAccion;
    }

    public void setNCodAccion(BigDecimal NCodAccion) {
        this.NCodAccion = NCodAccion;
    }

    public BigDecimal getNCodInspresencial() {
        return this.NCodInspresencial;
    }

    public void setNCodInspresencial(BigDecimal NCodInspresencial) {
        this.NCodInspresencial = NCodInspresencial;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegDetInspreAccionesId)) {
            return false;
        }
        SegDetInspreAccionesId castOther = (SegDetInspreAccionesId) other;

        return ((this.getNCodAccion() == castOther.getNCodAccion()) || (this.getNCodAccion() != null && castOther.getNCodAccion() != null && this.getNCodAccion().equals(castOther.getNCodAccion())))
                && ((this.getNCodInspresencial() == castOther.getNCodInspresencial()) || (this.getNCodInspresencial() != null && castOther.getNCodInspresencial() != null && this.getNCodInspresencial().equals(castOther.getNCodInspresencial())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodAccion() == null ? 0 : this.getNCodAccion().hashCode());
        result = 37 * result + (getNCodInspresencial() == null ? 0 : this.getNCodInspresencial().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
