package pe.com.segrop.sgsapp.domain;
// Generated 21-feb-2012 0:26:46 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SegDetAtributo generated by hbm2java
 */
public class SegDetAtributo implements java.io.Serializable {

    private SegDetAtributoId id;
    private SegCabEntidad segCabEntidad;
    private BigDecimal NCodEntidad;
    private BigDecimal NCodAtributo;
    private String VNombre;
    private String VNombreApp;
    private String VDescripcion;
    private String VComentario;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;

    public SegDetAtributo() {
        super();
    }

    public SegDetAtributo(SegDetAtributoId id, SegCabEntidad segCabEntidad) {
        this.id = id;
        this.segCabEntidad = segCabEntidad;
    }

    public SegDetAtributo(SegDetAtributoId id, SegCabEntidad segCabEntidad, BigDecimal NCodEntidad, BigDecimal NCodAtributo, String VNombre, String VNombreApp, String VDescripcion, String VComentario, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion) {
        this.id = id;
        this.segCabEntidad = segCabEntidad;
        this.NCodEntidad = NCodEntidad;
        this.NCodAtributo = NCodAtributo;
        this.VNombre = VNombre;
        this.VNombreApp = VNombreApp;
        this.VDescripcion = VDescripcion;
        this.VComentario = VComentario;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
    }

    public SegDetAtributoId getId() {
        return this.id;
    }

    public void setId(SegDetAtributoId id) {
        this.id = id;
    }

    public SegCabEntidad getSegCabEntidad() {
        return this.segCabEntidad;
    }

    public void setSegCabEntidad(SegCabEntidad segCabEntidad) {
        this.segCabEntidad = segCabEntidad;
    }

    public BigDecimal getNCodEntidad() {
        return NCodEntidad;
    }

    public void setNCodEntidad(BigDecimal NCodEntidad) {
        this.NCodEntidad = NCodEntidad;
    }

    public BigDecimal getNCodAtributo() {
        return NCodAtributo;
    }

    public void setNCodAtributo(BigDecimal NCodAtributo) {
        this.NCodAtributo = NCodAtributo;
    }

    public String getVNombre() {
        return VNombre;
    }

    public void setVNombre(String VNombre) {
        this.VNombre = VNombre;
    }

    public String getVNombreApp() {
        return VNombreApp;
    }

    public void setVNombreApp(String VNombreApp) {
        this.VNombreApp = VNombreApp;
    }

    public String getVDescripcion() {
        return this.VDescripcion;
    }

    public void setVDescripcion(String VDescripcion) {
        this.VDescripcion = VDescripcion;
    }

    public String getVComentario() {
        return VComentario;
    }

    public void setVComentario(String VComentario) {
        this.VComentario = VComentario;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }
}
