package pe.com.segrop.sgsapp.domain;
// Generated 16-mar-2012 2:45:34 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SegRelPermiso generated by hbm2java
 */
public class SegRelPermiso implements java.io.Serializable {

    private SegRelPermisoId id;
    private SegDetPerfil segDetPerfil;
    private BigDecimal NCodPerfil;
    private BigDecimal NCodObjeto;
    private BigDecimal NCodEmpresa;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;

    public SegRelPermiso() {
        super();
    }

    public SegRelPermiso(SegRelPermisoId id, SegDetPerfil segDetPerfil) {
        this.id = id;
        this.segDetPerfil = segDetPerfil;
    }

    public SegRelPermiso(SegRelPermisoId id, SegDetPerfil segDetPerfil, BigDecimal NCodPerfil, BigDecimal NCodObjeto, BigDecimal NCodEmpresa, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion) {
        this.id = id;
        this.segDetPerfil = segDetPerfil;
        this.NCodPerfil = NCodPerfil;
        this.NCodObjeto = NCodObjeto;
        this.NCodEmpresa = NCodEmpresa;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
    }

    public SegRelPermisoId getId() {
        return this.id;
    }

    public void setId(SegRelPermisoId id) {
        this.id = id;
    }

    public SegDetPerfil getSegDetPerfil() {
        return segDetPerfil;
    }

    public void setSegDetPerfil(SegDetPerfil segDetPerfil) {
        this.segDetPerfil = segDetPerfil;
    }

    public BigDecimal getNCodPerfil() {
        return NCodPerfil;
    }

    public void setNCodPerfil(BigDecimal NCodPerfil) {
        this.NCodPerfil = NCodPerfil;
    }

    public BigDecimal getNCodObjeto() {
        return NCodObjeto;
    }

    public void setNCodObjeto(BigDecimal NCodObjeto) {
        this.NCodObjeto = NCodObjeto;
    }

    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }
}
