package pe.com.segrop.sgsapp.domain;
// Generated 27-mar-2012 23:46:11 by Hibernate Tools 3.2.1.GA

/**
 * SegRelCuestionario generated by hbm2java
 */
public class SegRelCuestionario implements java.io.Serializable {

    private SegRelCuestionarioId id;

    public SegRelCuestionario() {
        super();
    }

    public SegRelCuestionario(SegRelCuestionarioId id) {
        this.id = id;
    }

    public SegRelCuestionarioId getId() {
        return this.id;
    }

    public void setId(SegRelCuestionarioId id) {
        this.id = id;
    }
}
