package pe.com.segrop.sgsapp.domain;
// Generated 15-jul-2012 21:05:20 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * SegRelUsuarioperfilId generated by hbm2java
 */
public class SegRelUsuarioperfilId implements java.io.Serializable {

    private BigDecimal NCodUsuario;
    private BigDecimal NCodPerfil;
    private BigDecimal NCodEmpresa;

    public SegRelUsuarioperfilId() {
        super();
    }

    public SegRelUsuarioperfilId(BigDecimal NCodUsuario, BigDecimal NCodPerfil, BigDecimal NCodEmpresa) {
        this.NCodUsuario = NCodUsuario;
        this.NCodPerfil = NCodPerfil;
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNCodUsuario() {
        return this.NCodUsuario;
    }

    public void setNCodUsuario(BigDecimal NCodUsuario) {
        this.NCodUsuario = NCodUsuario;
    }

    public BigDecimal getNCodPerfil() {
        return this.NCodPerfil;
    }

    public void setNCodPerfil(BigDecimal NCodPerfil) {
        this.NCodPerfil = NCodPerfil;
    }

    public BigDecimal getNCodEmpresa() {
        return this.NCodEmpresa;
    }

    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SegRelUsuarioperfilId)) {
            return false;
        }
        SegRelUsuarioperfilId castOther = (SegRelUsuarioperfilId) other;

        return ((this.getNCodUsuario() == castOther.getNCodUsuario()) || (this.getNCodUsuario() != null && castOther.getNCodUsuario() != null && this.getNCodUsuario().equals(castOther.getNCodUsuario())))
                && ((this.getNCodPerfil() == castOther.getNCodPerfil()) || (this.getNCodPerfil() != null && castOther.getNCodPerfil() != null && this.getNCodPerfil().equals(castOther.getNCodPerfil())))
                && ((this.getNCodEmpresa() == castOther.getNCodEmpresa()) || (this.getNCodEmpresa() != null && castOther.getNCodEmpresa() != null && this.getNCodEmpresa().equals(castOther.getNCodEmpresa())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getNCodUsuario() == null ? 0 : this.getNCodUsuario().hashCode());
        result = 37 * result + (getNCodPerfil() == null ? 0 : this.getNCodPerfil().hashCode());
        result = 37 * result + (getNCodEmpresa() == null ? 0 : this.getNCodEmpresa().hashCode());
        return result;
    }
}
