package pe.com.segrop.sgsapp.domain;
// Generated 15-jul-2012 21:05:20 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SegRelUsuarioperfil generated by hbm2java
 */
public class SegRelUsuarioperfil implements java.io.Serializable {

    private SegRelUsuarioperfilId id;
    private SegCabUsuario segCabUsuario;
    private BigDecimal NCodUsuario;
    private BigDecimal NCodPerfil;
    private BigDecimal NCodEmpresa;
    private BigDecimal NFlgActivo;
    private String VUsuCreacion;
    private Date DFecCreacion;
    private String VIpCreacion;
    private String VUsuModificacion;
    private Date DFecModificacion;
    private String VIpModificacion;

    public SegRelUsuarioperfil() {
        super();
    }

    public SegRelUsuarioperfil(SegRelUsuarioperfilId id, SegCabUsuario segCabUsuario, BigDecimal NCodUsuario, BigDecimal NCodPerfil, BigDecimal NCodEmpresa) {
        this.id = id;
        this.segCabUsuario = segCabUsuario;
        this.NCodUsuario = NCodUsuario;
        this.NCodPerfil = NCodPerfil;
        this.NCodEmpresa = NCodEmpresa;
    }

    public SegRelUsuarioperfil(SegRelUsuarioperfilId id, SegCabUsuario segCabUsuario, BigDecimal NCodUsuario, BigDecimal NCodPerfil, BigDecimal NCodEmpresa, BigDecimal NFlgActivo, String VUsuCreacion, Date DFecCreacion, String VIpCreacion, String VUsuModificacion, Date DFecModificacion, String VIpModificacion) {
        this.id = id;
        this.segCabUsuario = segCabUsuario;
        this.NCodUsuario = NCodUsuario;
        this.NCodPerfil = NCodPerfil;
        this.NCodEmpresa = NCodEmpresa;
        this.NFlgActivo = NFlgActivo;
        this.VUsuCreacion = VUsuCreacion;
        this.DFecCreacion = DFecCreacion;
        this.VIpCreacion = VIpCreacion;
        this.VUsuModificacion = VUsuModificacion;
        this.DFecModificacion = DFecModificacion;
        this.VIpModificacion = VIpModificacion;
    }

    public SegRelUsuarioperfilId getId() {
        return this.id;
    }

    public void setId(SegRelUsuarioperfilId id) {
        this.id = id;
    }

    public SegCabUsuario getSegCabUsuario() {
        return this.segCabUsuario;
    }

    public void setSegCabUsuario(SegCabUsuario segCabUsuario) {
        this.segCabUsuario = segCabUsuario;
    }

    /**
     * @return the NCodUsuario
     */
    public BigDecimal getNCodUsuario() {
        return NCodUsuario;
    }

    /**
     * @param NCodUsuario the NCodUsuario to set
     */
    public void setNCodUsuario(BigDecimal NCodUsuario) {
        this.NCodUsuario = NCodUsuario;
    }

    /**
     * @return the NCodPerfil
     */
    public BigDecimal getNCodPerfil() {
        return NCodPerfil;
    }

    /**
     * @param NCodPerfil the NCodPerfil to set
     */
    public void setNCodPerfil(BigDecimal NCodPerfil) {
        this.NCodPerfil = NCodPerfil;
    }

    /**
     * @return the NCodEmpresa
     */
    public BigDecimal getNCodEmpresa() {
        return NCodEmpresa;
    }

    /**
     * @param NCodEmpresa the NCodEmpresa to set
     */
    public void setNCodEmpresa(BigDecimal NCodEmpresa) {
        this.NCodEmpresa = NCodEmpresa;
    }

    public BigDecimal getNFlgActivo() {
        return this.NFlgActivo;
    }

    public void setNFlgActivo(BigDecimal NFlgActivo) {
        this.NFlgActivo = NFlgActivo;
    }

    public String getVUsuCreacion() {
        return this.VUsuCreacion;
    }

    public void setVUsuCreacion(String VUsuCreacion) {
        this.VUsuCreacion = VUsuCreacion;
    }

    public Date getDFecCreacion() {
        return this.DFecCreacion;
    }

    public void setDFecCreacion(Date DFecCreacion) {
        this.DFecCreacion = DFecCreacion;
    }

    public String getVIpCreacion() {
        return this.VIpCreacion;
    }

    public void setVIpCreacion(String VIpCreacion) {
        this.VIpCreacion = VIpCreacion;
    }

    public String getVUsuModificacion() {
        return this.VUsuModificacion;
    }

    public void setVUsuModificacion(String VUsuModificacion) {
        this.VUsuModificacion = VUsuModificacion;
    }

    public Date getDFecModificacion() {
        return this.DFecModificacion;
    }

    public void setDFecModificacion(Date DFecModificacion) {
        this.DFecModificacion = DFecModificacion;
    }

    public String getVIpModificacion() {
        return this.VIpModificacion;
    }

    public void setVIpModificacion(String VIpModificacion) {
        this.VIpModificacion = VIpModificacion;
    }
}
